// GENERATED by hand from design/assets.md › Keeper: static requires so Metro bundles every density.
export const KEEPER_BODY = {
  neutral: require("../../../assets/keeper/keeper-neutral.png"),
  smug: require("../../../assets/keeper/keeper-smug.png"),
  happy: require("../../../assets/keeper/keeper-happy.png"),
  wink: require("../../../assets/keeper/keeper-wink.png"),
  stern: require("../../../assets/keeper/keeper-stern.png"),
  soft: require("../../../assets/keeper/keeper-soft.png"),
  bored: require("../../../assets/keeper/keeper-bored.png"),
  side: require("../../../assets/keeper/keeper-side.png"),
  shocked: require("../../../assets/keeper/keeper-shocked.png"),
  shades: require("../../../assets/keeper/keeper-shades.png"),
} as const;
export const KEEPER_BUST = {
  neutral: require("../../../assets/keeper/keeper-bust-neutral.png"),
  smug: require("../../../assets/keeper/keeper-bust-smug.png"),
  happy: require("../../../assets/keeper/keeper-bust-happy.png"),
  wink: require("../../../assets/keeper/keeper-bust-wink.png"),
  stern: require("../../../assets/keeper/keeper-bust-stern.png"),
  soft: require("../../../assets/keeper/keeper-bust-soft.png"),
  bored: require("../../../assets/keeper/keeper-bust-bored.png"),
  side: require("../../../assets/keeper/keeper-bust-side.png"),
  shocked: require("../../../assets/keeper/keeper-bust-shocked.png"),
  shades: require("../../../assets/keeper/keeper-bust-shades.png"),
} as const;
export const KEEPER_PROP = {
  seal: require("../../../assets/keeper/keeper-happy-seal.png"),
  ledger: require("../../../assets/keeper/keeper-side-ledger.png"),
  lens: require("../../../assets/keeper/keeper-neutral-lens.png"),
  coin: require("../../../assets/keeper/keeper-smug-coin.png"),
  sack: require("../../../assets/keeper/keeper-shades-sack.png"),
  cup: require("../../../assets/keeper/keeper-bored-cup.png"),
  whisper: require("../../../assets/keeper/keeper-side-whisper.png"),
  scythe: require("../../../assets/keeper/keeper-stern-scythe.png"),
} as const;
export const KEEPER_POSE = {
  wave: require("../../../assets/keeper/keeper-pose-wave.png"),
  point: require("../../../assets/keeper/keeper-pose-point.png"),
  tap: require("../../../assets/keeper/keeper-pose-tap.png"),
  thumbs: require("../../../assets/keeper/keeper-pose-thumbs.png"),
  jump: require("../../../assets/keeper/keeper-pose-jump.png"),
  shrug: require("../../../assets/keeper/keeper-pose-shrug.png"),
  flip: require("../../../assets/keeper/keeper-pose-flip.png"),
  peek: require("../../../assets/keeper/keeper-pose-peek.png"),
  popin: require("../../../assets/keeper/keeper-pose-popin.png"),
} as const;
