// KEPT demo · shared builders. Screens register into window.KS.
(function () {
  const P = { Y: ['You', 'Y', '#C5F25C', '91% · 64d', '13050010'], R: ['Riya', 'R', '#F9A8D4', '94% · 71d', '26142321'], A: ['Arjun', 'A', '#FDE68A', '78% · 40d', '34323434'], D: ['Dev', 'D', '#93C5FD', '88% · 52d', '45201205'] };
  const OBJ = [['Dumbbell', 'dumbbell'], ['Book', 'book-open-variant'], ['Water bottle', 'bottle-soda-outline'], ['Guitar', 'guitar-acoustic'], ['Running shoe', 'shoe-sneaker'], ['Plant', 'sprout'], ['Skipping rope', 'jump-rope'], ['Yoga mat', 'yoga']];
  const GEST = { thumb: ['Thumbs up', 'thumb-up'], peace: ['Victory sign', 'hand-peace'], palm: ['Open palm', 'hand-back-right'] };
  const LEN = [3, 7, 14], STAKE = [500, 1000, 2500];
  const n = v => Number(v).toLocaleString('en-US');
  const B = (label, to, kind, ic) => ({ label, to, kind: kind || 'p', ic: ic || '' });
  const K = {
    P, OBJ, GEST, LEN, STAKE, n, B,
    T: (h, sub, o) => ({ k: 't', h, sub, ...(o || {}) }),
    TX: (t, o) => ({ k: 'tx', t, ...(o || {}) }),
    KP: (mood, line, o) => ({ k: 'kp', mood, line, ...(o || {}) }),
    CARD: o => ({ k: 'card', ...o }),
    ROWS: (items, lab) => ({ k: 'rows', items, lab }),
    R: (t, s, r, o) => ({ t, s, r, ...(o || {}) }),
    HP: (v, o) => ({ k: 'hp', v, ...(o || {}) }),
    GRID: (n, today, rows) => ({ k: 'grid', n, today, rows }),
    BIG: (v, l, o) => ({ k: 'big', v, l, ...(o || {}) }),
    CAM: o => ({ k: 'cam', ...o }),
    SHUT: to => ({ k: 'shut', to }),
    OPTS: (id, items, o) => ({ k: 'opts', id, items, ...(o || {}) }),
    INPUT: o => ({ k: 'input', ...o }),
    SEG: (items, o) => ({ k: 'seg', items, ...(o || {}) }),
    QR: (code, link) => ({ k: 'qr', code, link }),
    BRK: (items, lab) => ({ k: 'brk', items, lab }),
    BAN: (tone, ic, t, s, o) => ({ k: 'ban', tone, ic, t, s, ...(o || {}) }),
    SLOT: items => ({ k: 'slot', items }),
    COVER: o => ({ k: 'cover', ...o }),
    CHIPS: (items, o) => ({ k: 'chips', items, ...(o || {}) }),
    SIGN: (state, chip) => ({ k: 'sign', state, chip }),
    BARS: (lab, items) => ({ k: 'bars', lab, items }),
    BTNS: (items, dir) => ({ k: 'btns', items, dir: dir || 'row' }),
    NOTE: (t, ic) => ({ k: 'note', t, ic: ic || 'information-outline' }),
    RING: (v, l, p, c) => ({ k: 'ring', v, l, p, c }),
    ID: o => ({ k: 'id', ...o }),
    DAYS: (n, done, today, o) => ({ k: 'days', n, done, today, ...(o || {}) }),
    UP: (t, s) => ({ k: 'up', t, s }),
    SP: h => ({ k: 'sp', h }),
    sigScreen: (id, name, title, sub, next, sims, o) => ({ id, name, nav: { close: true }, auto: { to: next, ms: 2200 }, sim: sims, blocks: [{ k: 'sp', h: 60 }, { k: 'sign', state: 'pending', chip: (o && o.wallet) || 'Seeker Wallet' }, { k: 't', h: title, sub, al: 'center', pt: 26 }, { k: 'note', t: 'Waiting for your signature…', ic: 'timer-sand' }], ...(o || {}) }),
    cost: (stake, days, k) => Math.round(stake / days * Math.pow(1.5, k || 0)),
    avQuip: (s, base) => { const d = ((s.avV === 2 && s.av) || '13050010').split('').map(Number), tab = base ? 0 : (s.avTab ?? 0);
      const Q = [[0, ['Human. Bold, honestly.', 'A fox. Sly. I respect it.', 'Cat. Lands on its feet. Mostly.', 'Frog. Very online of you.', 'Bear. Patient. Good for 14 days.', 'A bot. Do bots keep their word?', "Skull? Hey, that's my look.", "Alien. You're not from around here."]],
        [2, ['Classic. Honest eyes.', 'Sleepy. Morning Oaths, huh?', 'Laser eyes. Bullish.', "Shades. Now we're talking."]],
        [3, ['No hat. Clean.', 'Beanie. Cosy.', 'Backwards cap. Classic.', 'A crown? Earn it.', "A halo. We'll see.", 'My visor! Flattered.']],
        [4, ['Hoodie. Builder energy.', 'Tee. Simple.', 'Chain. Flashy.', 'Jacket. Means business.', 'Turtleneck. Founder mode.']],
        [6, ['Nothing extra. Fair.', 'Ace behind the ear. Like me.', 'An earring. Nice.', 'Bandage. Rough week?']],
        [7, ['Lime. KEPT colours.', 'Violet. Royal.', 'Sky. Calm.', 'Pink. Loud. Good.', 'Sun. Optimist.', 'Mint. Fresh.', 'Night. Moody.', 'Ember. Spicy.']]][tab];
      return window.KK.KP(['shocked', 'smug', 'wink', 'happy', 'side', 'smug'][tab], Q[1][d[Q[0]] % Q[1].length], { size: 72, side: 'r', h: 84, anim: 'point' }); },
    NT: (items, lab, act) => ({ k: 'nt', items, lab, act }),
    HS: (items, o) => ({ k: 'hs', items, ...(o || {}) }),
    SEARCH: o => ({ k: 'search', ...o }),
    PROF: o => ({ k: 'prof', ...o }),
    AVB: o => ({ k: 'avb', ...(o || {}) }),
    PAL: { lime: ['#E6FF9E', '#A9D83C', '#1A2600'], vio: ['#DCD2FF', '#8E70F7', '#160B3A'], sky: ['#C4E8FF', '#3AA3F2', '#03213A'], pink: ['#FFD3EA', '#EF6BB0', '#3A0A22'], amber: ['#FFE8A8', '#F2B232', '#3A2400'], orange: ['#FFD1AE', '#F98A3C', '#3A1600'], white: ['#FFFFFF', '#D6D6D6', '#131313'] },
    grad: p => { const c = window.KK.PAL[p] || window.KK.PAL.white; return 'linear-gradient(150deg,' + c[0] + ',' + c[1] + ')'; },
    ink: p => (window.KK.PAL[p] || window.KK.PAL.white)[2],
    closes: h => h < 24 ? 'closes in ' + h + 'h' : Math.round(h / 24) + 'd left',
    bal: s => 4280 + (s['n:clm1'] ? 1186 : 0) + (s['n:fc1'] ? 5000 : 0) + (s['n:sw1'] ? Math.round([0.1, 0.25, 0.5, 1][s.swp ?? 2] * 9900) : 0),
    AVC: { SKN: ['#F6C9A8', '#C98E62', '#7A4A2E', '#F08A3C', '#7BC96F', '#A9B4C6', '#EFE8D8', '#9D86F9'], OC: ['#7C3AED', '#C5F25C', '#38BDF8', '#F472B6', '#FB923C', '#F2F0EA', '#2A2A33'], BG: ['#C5F25C', '#A78BFA', '#38BDF8', '#F9A8D4', '#FDE68A', '#5EEAD4', '#2E2E36', '#FB923C'] },
    BANS: ['linear-gradient(135deg,#C5F25C,#38BDF8)', 'linear-gradient(135deg,#A78BFA,#F472B6)', 'linear-gradient(135deg,#FB923C,#FDE68A)', 'linear-gradient(135deg,#38BDF8,#1E3A8A)', 'linear-gradient(135deg,#3A3A3A,#141414)'],
    NAMES: ['sam.skr', 'Sam K.', 'samkeeps'],
    BIOS: ['Lifting daily. Staking on myself.', 'Building in public, one kept day at a time.', 'Will out-keep you. Try me.'],
    mySoc: s => [((s['tg:sx'] ?? 1) && ['X', null, '@samkeeps', 'toast:Opening X']), ((s['tg:stg'] ?? 0) && [null, 'send-outline', '@sam_k', 'toast:Opening Telegram']), ((s['tg:sdc'] ?? 0) && [null, 'forum-outline', 'sam#0420', 'toast:Opening Discord']), ((s['tg:sfc'] ?? 0) && [null, 'arch', '@sam', 'toast:Opening Farcaster'])].filter(Boolean),
    CATS: ['All', 'Fitness', 'Reading', 'Hydration', 'Music', 'Mind', 'Outdoors'],
    INBOX: [
      { id: 'inv1', need: 1, p: 'R', t: 'Riya invited you to Dawn Run', s: '7 days · 1,000 SKR each · Dev is in', time: '2h', bdg: 'email-outline', bpal: 'vio', to: 'E2', btns: [['Accept', 'do:inv1|E2', 'l'], ['Decline', 'do:inv1||Invite declined', 's']] },
      { id: 'rev1', need: 1, p: 'D', t: 'Dev wants your vote', s: 'Iron Week · photo 2 failed 3 times · 41h left', time: '3h', bdg: 'eye-outline', bpal: 'vio', to: 'G1', btns: [['Review photo', 'G1', 'p']] },
      { id: 'clm1', need: 1, k: 'smug', ic: 'hand-coin-outline', pal: 'lime', t: '1,186 SKR ready to claim', s: 'Hydra 14 ended Sunday', time: '1d', to: 'J1', btns: [['Claim', 'J1', 'l']] },
      { id: 'rm1', need: 1, k: 'wink', ic: 'sword-cross', pal: 'orange', t: 'Rematch Guitar Days?', s: 'Win back 500 SKR · closes in 6d 23h', time: '2d', to: 'R1', btns: [['See Rematch', 'R1', 's']] },
      { id: 'ng1', p: 'R', t: 'Riya nudged you', s: 'Iron Week · photo 2 is still due', time: '20m', bdg: 'bell-ring', bpal: 'lime', to: 'do:ng1|F4' },
      { id: 'rc1', k: 'side', ic: 'newspaper-variant-outline', pal: 'white', t: 'Yesterday, settled', s: "Arjun missed · +43 SKR to you", time: '00:01', to: 'do:rc1|B5' },
      { id: 'st1', ic: 'play', pal: 'sky', t: 'Hydrate Week started', s: 'Day 1 is today · 40 in', time: 'Mon', to: 'do:st1|H3' },
      { id: 'fl1', ic: 'trophy-outline', pal: 'amber', t: 'Drift posted a new Bounty', s: 'Hydrate Week · 50,000 SKR pool', time: 'Mon', to: 'do:fl1|H2' }],
    HIST: [
      { m: 'October', n: 'Hydra 14', s: 'Kept by 3 of 4 · ended Sun 5', r: '+186', ic: 'trophy-outline', k: 'kept', to: 'D4' },
      { m: 'October', n: 'Pages Sprint · Rematch', s: 'Kept every day · recovered 500', r: '+500', ic: 'sword-cross', k: 'rematch', to: 'R4' },
      { m: 'October', n: 'Guitar Days', s: 'Broke on day 6', r: '−1,000', ic: 'guitar-acoustic', k: 'broken', to: 'D3' },
      { m: 'September', n: 'Iron Week', s: 'Kept · 7 of 7', r: '+72', ic: 'dumbbell', k: 'kept', to: 'D4' },
      { m: 'September', n: 'Dawn Run', s: 'Solo · kept 7 of 7', r: '±0', ic: 'shoe-sneaker', k: 'kept', to: 'D4' },
      { m: 'September', n: 'Cold Showers', s: 'Solo · broke on day 4', r: '−500', ic: 'water-outline', k: 'broken', to: 'D3' },
      { m: 'September', n: 'Read 20 pages', s: 'Kept · missed 1 day', r: '+12', ic: 'book-open-variant', k: 'kept', to: 'D4' },
      { m: 'September', n: 'Mat Mornings', s: 'Kept by 2 of 3', r: '+140', ic: 'yoga', k: 'kept', to: 'D4' }],
    BOUNTIES: [
      { n: 'Hydrate Week', by: 'Drift', ic: 'bottle-soda-outline', pal: 'sky', pool: 50000, in: 40, close: 5, cat: 'Hydration', el: 1, to: 'H2' },
      { n: 'Northbound Run Club', by: 'Northbound', ic: 'shoe-sneaker', pal: 'pink', pool: 120000, in: 212, close: 48, cat: 'Fitness', el: 0, to: 'H2·no' },
      { n: 'Mat Month', by: 'Lotus', ic: 'yoga', pal: 'vio', pool: 30000, in: 88, close: 30, cat: 'Mind', el: 1, to: 'H2' },
      { n: 'Sol Strings', by: '@riffs', ic: 'guitar-acoustic', pal: 'amber', pool: 8000, in: 58, close: 9, cat: 'Music', el: 1, to: 'H2' },
      { n: 'Dawn Pages', by: 'Inkwell', ic: 'book-open-variant', pal: 'vio', pool: 20000, in: 58, close: 20, cat: 'Reading', el: 1, to: 'H2' },
      { n: 'Iron October', by: 'Forge Gym', ic: 'dumbbell', pal: 'lime', pool: 75000, in: 340, close: 70, cat: 'Fitness', el: 1, to: 'H2' },
      { n: 'Green Thumb', by: 'Sprout Co', ic: 'sprout', pal: 'lime', pool: 12000, in: 31, close: 12, cat: 'Outdoors', el: 1, to: 'H2' },
      { n: 'Rope 1k', by: 'SkipLab', ic: 'jump-rope', pal: 'pink', pool: 15000, in: 120, close: 3, cat: 'Fitness', el: 0, to: 'H2·no' }],
    ACT: [
      { d: 'TODAY', t: 'Kept Iron Week · day 3', s: 'Photo 2 passed · 21:04', ic: 'check-bold', c: 2 },
      { d: 'TODAY', t: 'Photo 1 passed', s: 'Iron Week · 07:58', ic: 'camera', c: 2 },
      { d: 'YESTERDAY', t: "+43 SKR from Arjun's miss", s: 'Iron Week · settled 00:00', r: '+43', ic: 'sack', c: 1 },
      { d: 'YESTERDAY', t: 'Kept Read 20 pages', s: 'Solo · day 8', ic: 'check-bold', c: 2 },
      { d: 'YESTERDAY', t: "Voted on Dev's photo", s: 'Approved', ic: 'vote-outline', c: 3 },
      { d: 'MON 6 OCT', t: 'Staked into Iron Week', s: '1,000 SKR', r: '−1,000', ic: 'arrow-top-right', c: 1 },
      { d: 'MON 6 OCT', t: 'Joined Hydrate Week', s: 'Bounty by Drift', ic: 'trophy-outline', c: 3 },
      { d: 'SUN 5 OCT', t: 'Claimed Hydra 14', s: '1,186 SKR', r: '+1,186', ic: 'hand-coin-outline', c: 1 },
      { d: 'SUN 5 OCT', t: 'Guitar Days broke', s: 'HP hit 0 on day 6', r: '−1,000', ic: 'fire', c: 3 }],
  };
  window.KK = K;
  window.KS = window.KS || [];
})();
