// Copies the IDL + TS types generated by `anchor build` into the app.
// Run after every program change: npm run sync-idl
const fs = require("fs");
const path = require("path");

const target = path.join(__dirname, "..", "..", "program", "target");
const out = path.join(__dirname, "..", "src", "chain", "idl");
const files = [
  ["idl/kept_test.json", "kept_test.json"],
  ["types/kept_test.ts", "kept_test.ts"],
];

fs.mkdirSync(out, { recursive: true });
for (const [from, to] of files) {
  const src = path.join(target, from);
  if (!fs.existsSync(src)) {
    console.error(`Missing ${src}. Run \`anchor build\` in ../program first.`);
    process.exit(1);
  }
  fs.copyFileSync(src, path.join(out, to));
  console.log(`copied ${from} -> src/chain/idl/${to}`);
}
