// Anchor handle for kept_test. The IDL is generated by `anchor build` and copied here by
// `npm run sync-idl`; the program ID always comes from config, never from the IDL file.

import { Program, Provider } from "@anchor-lang/core";

import { config } from "../config";
import { connection } from "./connection";
import idlJson from "./idl/kept_test.json";
import type { KeptTest } from "./idl/kept_test";

const idl = { ...idlJson, address: config.programId.toBase58() } as unknown as KeptTest;

/** Read + instruction-building only: transactions are signed by the wallet, not Anchor. */
const readOnlyProvider = { connection } as Provider;

export const program = new Program<KeptTest>(idl, readOnlyProvider);

/** Program error codes -> names, straight from the IDL (6000 InvalidSlot, ...). */
export const programErrors: Record<number, { name: string; msg?: string }> = Object.fromEntries(
  (idlJson.errors ?? []).map((e: { code: number; name: string; msg?: string }) => [e.code, { name: e.name, msg: e.msg }]),
);
