import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Alert, AppState, Image, Linking, Pressable, ScrollView, Switch, Text, TextInput, View } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import * as Notifications from "expo-notifications";
import QRCode from "react-native-qrcode-svg";
import { PublicKey } from "@solana/web3.js";
import { getAssociatedTokenAddress, getAccount, TOKEN_2022_PROGRAM_ID, TOKEN_PROGRAM_ID } from "@solana/spl-token";
import { sha256 } from "@noble/hashes/sha2.js";
import { WalletScreen, styles } from "./WalletScreen";
import { config } from "../config";
import { api, signIn, signOut } from "../backend";
import { cancelOath, claimOath, createOath, fetchOath, joinOath, migrateKeeper, OathView, settleOath, startOath } from "../chain/oaths";
import { connection } from "../chain/connection";
import { log } from "../debug/log";

const OBJECTS=["dumbbell","book","water_bottle","guitar","running_shoe","plant","skipping_rope","yoga_mat"];
const GESTURES=["thumbs_up","victory","open_palm","closed_fist","pointing_up"];
const usdOptions=[5,10,25] as const;
type Props={wallet:PublicKey|null;onWalletChange:(w:PublicKey|null)=>void;signedIn:boolean;onSignedInChange:(v:boolean)=>void;onShowConsole:()=>void};

export function TestHarness({wallet,onWalletChange,signedIn,onSignedInChange,onShowConsole}:Props){
 const [busy,setBusy]=useState(false),[genesis,setGenesis]=useState<{genesis:boolean;mocked:boolean;genesisMint:string|null}|null>(null);
 const [sol,setSol]=useState("—"),[skr,setSkr]=useState("—"),[profile,setProfile]=useState("—");
 const [goal,setGoal]=useState("Daily practice"),[objectId,setObjectId]=useState(0),[days,setDays]=useState(3),[usd,setUsd]=useState(10),[solo,setSolo]=useState(false),[debugShort,setDebugShort]=useState(false);
 const [oathInput,setOathInput]=useState(""),[code,setCode]=useState(""),[oath,setOath]=useState<OathView|null>(null),[invite,setInvite]=useState("");
 const [goalText,setGoalText]=useState<string|null>(null);
 const [cameraPermission,requestCameraPermission]=useCameraPermissions(); const camera=useRef<CameraView>(null);
 const [forcePass,setForcePass]=useState(false),[threshold,setThreshold]=useState(0.7),[scan,setScan]=useState(false),[photos,setPhotos]=useState<Array<{wallet:string;image:string}>>([]);
 const [target,setTarget]=useState<{object:string;gesture:string}|null>(null);
 const backendReady=signedIn&&genesis?.genesis===true;

 const run=async(fn:()=>Promise<unknown>,showConsole=true)=>{setBusy(true);try{await fn();}catch(e){Alert.alert("Action failed",e instanceof Error?e.message:String(e));log.error("Harness action failed",e instanceof Error?e.message:String(e),String(e));}finally{setBusy(false);if(showConsole)onShowConsole();}};
 const refresh=async()=>{if(!wallet)return;const [lamports,raw]=await Promise.all([connection.getBalance(wallet,"confirmed"),keeperInfo(wallet)]);setSol((lamports/1e9).toFixed(4));setProfile(raw?.legacy?"V3 Keeper found · migrate when ready":raw?`Streak ${raw.streak} · Best ${raw.best} · kept ${raw.kept} · missed ${raw.missed}`:"Keeper not initialized");log.wallet("Keeper status refreshed",raw?.legacy?"V3 record":raw?"V4 record":"not initialized");await refreshSkr(wallet);if(oath){const updated=await fetchOath(new PublicKey(oath.address));setOath(updated);}};
 const refreshSkr=async(w:PublicKey)=>{try{if(!config.stakeMint){setSkr("Mint not configured");return;}const mint=new PublicKey(config.stakeMint),mintAcc=await connection.getAccountInfo(mint,"confirmed");const tokenProgram=mintAcc?.owner.equals(TOKEN_2022_PROGRAM_ID)?TOKEN_2022_PROGRAM_ID:TOKEN_PROGRAM_ID;const ata=await getAssociatedTokenAddress(mint,w,false,tokenProgram);const bal=await getAccount(connection,ata,"confirmed",tokenProgram);setSkr((Number(bal.amount)/1e6).toLocaleString());}catch{setSkr("0");}};
 const updateMe=async()=>{const m=await api<{genesis:boolean;mocked:boolean;genesisMint:string|null}>("/api/me","GET");setGenesis(m);};
 const refreshRef=useRef(refresh),updateMeRef=useRef(updateMe);
 useEffect(()=>{refreshRef.current=refresh;updateMeRef.current=updateMe;});
 useEffect(()=>{if(wallet){void refresh().catch(e=>log.error("Balance refresh failed",String(e),String(e)));} },[wallet]);
 useEffect(()=>{if(signedIn)void updateMe().catch(()=>onSignedInChange(false));},[signedIn]);
 useEffect(()=>{const sub=AppState.addEventListener("change",state=>{if(state!=="active"||!wallet)return;void refreshRef.current().catch(e=>log.error("Foreground refresh failed",String(e),String(e)));if(signedIn)void updateMeRef.current().catch(e=>log.error("Foreground eligibility refresh failed",String(e),String(e)));});return()=>sub.remove();},[wallet,signedIn]);
 useEffect(()=>{const listener=Notifications.addNotificationReceivedListener(n=>log.tx("Push notification received",JSON.stringify(n.request.content)));return()=>listener.remove();},[]);
 useEffect(()=>{const applyUrl=(url:string|null)=>{if(!url)return;const m=url.match(/^kept:\/\/join\/([^/?#]+)/);if(m){setCode(decodeURIComponent(m[1]));log.wallet("Invite deep link opened",url);}};void Linking.getInitialURL().then(applyUrl);const sub=Linking.addEventListener("url",e=>applyUrl(e.url));return()=>sub.remove();},[]);

 const signInAction=()=>run(async()=>{if(!wallet)throw new Error("Connect a wallet first");await signIn(wallet);onSignedInChange(true);await updateMe();log.wallet("Signed in with Solana");});
 const faucet=()=>run(async()=>{const r=await api<{signature:string;amount:string}>("/api/faucet","POST",{});log.tx("Test SKR faucet",r.signature);await refresh();});
 const registerPush=()=>run(async()=>{const perm=await Notifications.requestPermissionsAsync();if(!perm.granted)throw new Error("Notification permission was declined");const r=await Notifications.getDevicePushTokenAsync();await api("/api/push-token","POST",{token:r.data});log.tx("Push token registered",String(r.data));});
 const migrate=()=>run(async()=>{if(!wallet)throw new Error("Connect a wallet first");await migrateKeeper(wallet);await refresh();});

 const create=()=>run(async()=>{
  if(!wallet)throw new Error("Connect a wallet first");
  if(!solo&&!backendReady)throw new Error("Group Oaths require verified Genesis eligibility. Add this wallet to the Render mock allowlist or use an eligible Seeker wallet.");
  const id=BigInt(Date.now())*1000n+BigInt(Math.floor(Math.random()*1000));const stake=solo?0n:BigInt(usd*100)*1_000_000n;
  const result=await createOath(wallet,{id,goal:goal.trim(),objectId,days,daySeconds:__DEV__&&debugShort?120:86400,tzOffset:-new Date().getTimezoneOffset(),stake,solo});
  const info=await fetchOath(result.oath);if(!info)throw new Error("Oath was created but could not be read");setOath(info);setOathInput(info.address);if(backendReady){await api("/api/oaths/details","POST",{oath:info.address,goalText:goal.trim()});setGoalText(goal.trim());await api("/api/oaths/watch","POST",{oath:info.address});}
  if(!solo){const inv=await api<{code:string;deepLink:string}>("/api/invites","POST",{oath:info.address});setCode(inv.code);setInvite(inv.deepLink);}
  await refresh();
 });
 const resolveInvite=()=>run(async()=>{const r=await api<{oath:{address:string;status:number};goalText:string|null;alreadyStarted:boolean}>(`/api/invites/${encodeURIComponent(code)}`,"GET");setOathInput(r.oath.address);setGoalText(r.goalText);if(r.alreadyStarted)throw new Error("This Oath has already started");});
 const join=()=>run(async()=>{if(!wallet)throw new Error("Connect a wallet first");let oathAddress=oathInput;if(code){const inv=await api<any>(`/api/invites/${encodeURIComponent(code)}`,"GET");oathAddress=inv.oath.address;setGoalText(inv.goalText);}else if(oathInput.startsWith("kept://join/")){const inviteCode=oathInput.split("/").pop()!;const inv=await api<any>(`/api/invites/${encodeURIComponent(inviteCode)}`,"GET");oathAddress=inv.oath.address;setGoalText(inv.goalText);}if(!oathAddress)throw new Error("Enter an invite code or Oath address");await joinOath(wallet,new PublicKey(oathAddress));const v=await fetchOath(new PublicKey(oathAddress));setOath(v);setOathInput(oathAddress);await api("/api/oaths/watch","POST",{oath:oathAddress});});
 const start=()=>run(async()=>{if(!wallet||!oath)throw new Error("Load an Oath first");await startOath(wallet,new PublicKey(oath.address));const v=await fetchOath(new PublicKey(oath.address));setOath(v);});
 const cancel=()=>run(async()=>{if(!wallet||!oath)throw new Error("Load an Oath first");await cancelOath(wallet,new PublicKey(oath.address));setOath(await fetchOath(new PublicKey(oath.address)));});
 const loadOath=()=>run(async()=>{if(!oathInput)throw new Error("Enter an Oath address");const v=await fetchOath(new PublicKey(oathInput));if(!v)throw new Error("Oath not found on chain");setOath(v);if(backendReady&&v.members.some(m=>m.wallet===wallet?.toBase58())){const d=await api<{goalText:string|null}>(`/api/oaths/${v.address}/details`,"GET");setGoalText(d.goalText);}if(backendReady)await api("/api/oaths/watch","POST",{oath:v.address});});

 const captureProof=()=>run(async()=>{if(!wallet||!oath||!target)throw new Error("Load an active Oath first");if(!cameraPermission?.granted){const p=await requestCameraPermission();if(!p.granted)throw new Error("Camera permission is required");}
  const image=await camera.current?.takePictureAsync({quality:.82,base64:true});if(!image?.base64)throw new Error("Camera did not return an image");
  const day=Math.floor((Math.floor(Date.now()/1000)-oath.startTs)/oath.daySeconds);
  // The force-pass path exists only in development. No detector weights are bundled yet.
  if(!forcePass)throw new Error("On-device object and gesture models are not bundled. Enable Force detection pass in this debug build to test the verifier flow.");
  const detection={object:{label:target.object,confidence:Math.max(.7,threshold)},gesture:{label:target.gesture,confidence:Math.max(.7,threshold)},target};
  log.derive("Model output (debug forced)",JSON.stringify({object:detection.object,gesture:detection.gesture,target,threshold}));
  const result=await api<{signature:string}>("/api/proof","POST",{oath:oath.address,dayIndex:day,photo:image.base64,detection});log.tx("Proof recorded by verifier",result.signature);setOath(await fetchOath(new PublicKey(oath.address)));
 });
 const inviteCreate=()=>run(async()=>{if(!oath)throw new Error("Load an Oath first");const i=await api<{code:string;deepLink:string}>("/api/invites","POST",{oath:oath.address});setCode(i.code);setInvite(i.deepLink);});
 const settle=()=>run(async()=>{if(!wallet||!oath)throw new Error("Load an Oath first");const preview=calculatePreview(oath);log.derive("Settlement math preview",JSON.stringify(preview,null,2));await settleOath(wallet,new PublicKey(oath.address));setOath(await fetchOath(new PublicKey(oath.address)));});
 const claim=()=>run(async()=>{if(!wallet||!oath)throw new Error("Load an Oath first");await claimOath(wallet,new PublicKey(oath.address));setOath(await fetchOath(new PublicKey(oath.address)));await refresh();});
 const groupPhotos=(day:number)=>run(async()=>{if(!oath)throw new Error("Load an Oath first");const p=await api<{photos:Array<{wallet:string;image:string}>}>(`/api/photos/${oath.address}/${day}`,"GET");setPhotos(p.photos);});
 const nudge=(recipient:string,day:number)=>run(async()=>{if(!oath)throw new Error("Load an Oath first");await api("/api/nudges","POST",{oath:oath.address,recipient,dayIndex:day});Alert.alert("Nudge sent","Your friend has been nudged.");});

 const currentDay=oath&&oath.status===1?Math.floor((Math.floor(Date.now()/1000)-oath.startTs)/oath.daySeconds):-1;
 useEffect(()=>{if(!oath||oath.status!==1)return;const day=Math.max(0,currentDay);const d=sha256(new TextEncoder().encode(`${oath.oathId}:${day}`));const n=(d[0]+d[1]*256+d[2]*65536+d[3]*16777216)>>>0;setTarget({object:OBJECTS[oath.objectId]??OBJECTS[0],gesture:GESTURES[n%GESTURES.length]});},[oath?.address,oath?.status,currentDay]);
 return <ScrollView contentContainerStyle={{paddingBottom:36}}>
  <WalletScreen wallet={wallet} onChange={w=>{onWalletChange(w);if(!w){onSignedInChange(false);void signOut();}}}/>
  <Box title="Sign-in and eligibility"><Text style={styles.label}>{signedIn?`Signed in · Genesis ${genesis?.genesis?genesis.mocked?"MOCKED":"verified":"missing"}`:"Sign in with a wallet message to use the backend"}</Text><Row><Btn label={signedIn?"Refresh Genesis status":"Sign-in with Solana"} disabled={busy||!wallet} onPress={signedIn?()=>void run(updateMe):signInAction}/><Btn label="Sign out" disabled={!signedIn} onPress={()=>{void signOut();onSignedInChange(false);setGenesis(null);}}/></Row>{genesis?.genesisMint?<Text style={styles.label}>Genesis mint: {genesis.genesisMint}</Text>:null}{signedIn&&genesis&&!genesis.genesis?<Text style={styles.label}>Backend features and group invites are gated until this wallet has verified Genesis eligibility.</Text>:null}</Box>
  <Box title="Balances"><Text style={styles.label}>SOL {sol} · test SKR {skr}</Text><Row><Btn label="Refresh" disabled={!wallet||busy} onPress={()=>void run(refresh)}/><Btn label="Get test SKR · 5,000" disabled={!wallet||!backendReady||busy} onPress={faucet}/><Btn label="Register push" disabled={!backendReady||busy} onPress={registerPush}/></Row><Text style={styles.label}>{profile}</Text>{profile.startsWith("V3 Keeper")?<Btn label="Migrate Keeper to V4" disabled={!wallet||busy} onPress={migrate}/>:null}</Box>
  <Box title="Create Oath"><TextInput style={styles.input} value={goal} onChangeText={setGoal} placeholder="One thing each day" placeholderTextColor="#888"/><Text style={styles.label}>Object to detect</Text><ScrollRow>{OBJECTS.map((o,i)=><Choice key={o} label={o} active={i===objectId} onPress={()=>setObjectId(i)}/>)}</ScrollRow><Row>{[3,7,14].map(d=><Choice key={d} label={`${d} days`} active={days===d} onPress={()=>setDays(d)}/>)}</Row><Row><Choice label="Solo · no stake" active={solo} onPress={()=>setSolo(true)}/><Choice label="Group · stake SKR" active={!solo} onPress={()=>setSolo(false)}/></Row>{!solo?<Row>{usdOptions.map(n=><Choice key={n} label={`$${n} · ${n*100} SKR`} active={usd===n} onPress={()=>setUsd(n)}/>)}</Row>:null}{__DEV__?<Row><Text style={styles.label}>2 minute day (debug)</Text><Switch value={debugShort} onValueChange={setDebugShort}/></Row>:null}<Btn label="Create Oath" disabled={!wallet||busy||!signedIn} onPress={create}/></Box>
  <Box title="Invite or load Oath"><TextInput style={styles.input} value={code} onChangeText={setCode} placeholder="Invite code" placeholderTextColor="#888"/><Row><Btn label="Resolve invite" disabled={!backendReady||busy||!code} onPress={resolveInvite}/><Btn label="Join Oath" disabled={!wallet||!backendReady||busy} onPress={join}/><Btn label="Scan QR" disabled={!backendReady||busy} onPress={()=>void run(async()=>{if(scan){setScan(false);return;}if(!cameraPermission?.granted){const p=await requestCameraPermission();if(!p.granted)throw new Error("Camera permission is required to scan invites");}setScan(true);},false)}/></Row>{scan?<CameraView style={{height:220}} barcodeScannerSettings={{barcodeTypes:["qr"]}} onBarcodeScanned={e=>{setScan(false);if(e.data.startsWith("kept://join/")){setCode(e.data.slice("kept://join/".length));void run(async()=>{const r=await api<any>(`/api/invites/${encodeURIComponent(e.data.split("/").pop()!)}`,"GET");setOathInput(r.oath.address);setGoalText(r.goalText);setOath(await fetchOath(new PublicKey(r.oath.address)));},false);}}}/>:null}<TextInput style={styles.input} value={oathInput} onChangeText={setOathInput} placeholder="Oath address" placeholderTextColor="#888" autoCapitalize="none"/><Row><Btn label="Load Oath" disabled={busy||!oathInput} onPress={loadOath}/><Btn label="Create invite" disabled={!backendReady||!oath||busy} onPress={inviteCreate}/></Row>{invite?<View style={{alignItems:"center",gap:8,padding:8}}><QRCode value={invite} size={150}/><Text selectable style={styles.label}>{invite}</Text><Text selectable style={styles.label}>Invite code: {code}</Text></View>:null}</Box>
  {oath?<Box title="Oath details">{goalText?<Text style={styles.label}>Goal: {goalText}</Text>:null}<Text style={styles.label}>Goal hash {oath.goalHash.slice(0,18)}… · {OBJECTS[oath.objectId]} · {oath.numDays} days · {oath.daySeconds}s/day</Text><Text selectable style={styles.label}>{oath.address}</Text><Text style={styles.label}>Status {(["Open","Active","Settled","Cancelled"] as const)[oath.status]??"?"} · day {currentDay+1}/{oath.numDays} · stake {Number(oath.stakeAmount)/1e6} SKR</Text><Row>{oath.status===0?<><Btn label="Start (creator)" disabled={busy||wallet?.toBase58()!==oath.creator} onPress={start}/><Btn label="Cancel (Open only)" disabled={busy||wallet?.toBase58()!==oath.creator} onPress={cancel}/></>:null}{oath.status===1?<Btn label="Settle (after end)" disabled={busy||Date.now()/1000<oath.startTs+oath.numDays*oath.daySeconds} onPress={settle}/>:null}{oath.status===2||oath.status===3?<Btn label="Claim payout" disabled={busy} onPress={claim}/>:null}</Row>
   {oath.status===1?<Text style={styles.label}>Payout preview (10% fee on lost stakes): {JSON.stringify(calculatePreview(oath))}</Text>:null}
   <Text style={styles.label}>Member × day check-in grid</Text>{oath.members.map(m=><View key={m.wallet} style={{paddingVertical:5}}><Text selectable style={styles.label}>{m.wallet===wallet?.toBase58()?"You":`${m.wallet.slice(0,5)}…${m.wallet.slice(-4)}`}{m.claimed?" · claimed":""}{oath.status>=2?` · payout ${Number(m.payout)/1e6} SKR`:""}</Text><Row>{Array.from({length:oath.numDays},(_,d)=>{const kept=(m.daysKept&(1<<d))!==0;return <Pressable key={d} onPress={()=>kept&&backendReady?void groupPhotos(d):undefined} style={{padding:7,backgroundColor:kept?"#255c3b":"#303035",marginRight:4,borderRadius:4}}><Text style={{color:"white"}}>{d+1}{kept?" ✓":" ·"}</Text></Pressable>})}{wallet&&m.wallet!==wallet.toBase58()&&oath.status===1?<Btn label="Nudge" disabled={!backendReady||busy||currentDay<0} onPress={()=>void nudge(m.wallet,currentDay)}/>:null}</Row></View>)}
  </Box>:null}
  {oath?.status===1?<Box title="Daily proof · camera"><Text style={styles.label}>Today's target: {target?.object??"load Oath"} + {target?.gesture??"…"} · {Math.max(0,currentDay)+1}/{oath.numDays}</Text>{!cameraPermission?.granted?<Btn label="Allow camera" disabled={busy} onPress={()=>void requestCameraPermission()}/>:<CameraView ref={camera} style={{height:240}} facing="back"/>}{__DEV__?<Row><Text style={styles.label}>Force detection pass (debug)</Text><Switch value={forcePass} onValueChange={setForcePass}/></Row>:null}{__DEV__?<Row><Text style={styles.label}>Confidence threshold {threshold.toFixed(2)}</Text><Btn label="−" onPress={()=>setThreshold(Math.max(.4,threshold-.05))}/><Btn label="+" onPress={()=>setThreshold(Math.min(.99,threshold+.05))}/></Row>:null}<Btn label="Capture & submit proof" disabled={!backendReady||busy||!wallet||!target||currentDay<0||currentDay>=oath.numDays} onPress={captureProof}/></Box>:null}
  {photos.length?<Box title="Member photos"><Row>{photos.map(p=><View key={p.wallet} style={{gap:4}}><Text style={styles.label}>{p.wallet.slice(0,8)}…</Text><Image source={{uri:p.image}} style={{width:150,height:170}}/></View>)}</Row></Box>:null}
  {!signedIn?<Text style={[styles.label,{padding:14}]}>Sign-in is required for invite, proof, photos, nudge, faucet and push endpoints.</Text>:null}
  {busy?<ActivityIndicator color="#f5b94a" style={{padding:8}}/>:null}
 </ScrollView>;
}

async function keeperInfo(wallet:PublicKey){const [pda]=PublicKey.findProgramAddressSync([Buffer.from("keeper"),wallet.toBuffer()],config.programId);const a=await connection.getAccountInfo(pda,"confirmed");if(!a||a.data.length<61){log.derive("Keeper account lookup",a?`data too short: ${a.data.length}`:"account missing");return null;}const marker=String.fromCharCode(...Array.from(a.data.subarray(61,69)));const legacy=a.data.length>=69&&marker!=="KEPTV4!!";log.derive("Keeper account layout",JSON.stringify({bytes:a.data.length,marker,ownerMatches:a.owner.equals(config.programId)}));if(legacy)return{legacy:true as const};return{legacy:false as const,streak:a.data.readUInt16LE(40),best:a.data.readUInt16LE(42),kept:a.data.readUInt32LE(44),missed:a.data.readUInt32LE(48)};}
function calculatePreview(o:OathView){const stake=BigInt(o.stakeAmount);const full=(1<<o.numDays)-1;const won=o.members.map(m=>m.daysKept===full);const keepers=won.filter(Boolean).length,broken=won.length-keepers;const payouts=won.map(()=>0n);const lost=stake*BigInt(broken);let fee=0n,dust=0n,share=0n;const bps=1000n;if(stake===0n||broken===0){if(stake>0n)payouts.fill(stake);}else if(keepers===0){const eachFee=stake*bps/10000n;payouts.fill(stake-eachFee);fee=eachFee*BigInt(won.length);}else{fee=lost*bps/10000n;const distributable=lost-fee;share=distributable/BigInt(keepers);let i=0;for(const success of won){if(success)payouts[i]=stake+share;i++;}dust=distributable-share*BigInt(keepers);}return{steps:{stakePerMember:stake.toString(),keptMembers:keepers,brokenMembers:broken,lostStake:lost.toString(),feeBps:1000,fee:fee.toString(),sharedAmountPerKeeper:share.toString(),roundingDustToTreasury:dust.toString()},payouts:o.members.map((m,i)=>({wallet:m.wallet,amount:payouts[i].toString()})),treasuryFeeAndDust:(fee+dust).toString()};}
function Box({title,children}:{title:string;children:any}){return <View style={styles.box}><Text style={styles.title}>{title}</Text>{children}</View>}
function Row({children}:{children:any}){return <View style={styles.row}>{children}</View>}
function ScrollRow({children}:{children:any}){return <ScrollView horizontal>{children}</ScrollView>}
function Btn({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable style={[styles.btn,disabled&&styles.btnDisabled]} disabled={disabled} onPress={onPress}><Text style={styles.btnText}>{label}</Text></Pressable>}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.btn,active&&styles.btnSelected]}><Text style={styles.btnText}>{label}</Text></Pressable>}
